s='python is very easy language'
print(s.upper())
print(s.lower())
print(s.capitalize())
print(s.title())
print(s.replace('easy', 'hard'))
print(''.join(s))
print(s.find('is'))
print(s.split())
print(s.find('hi'))
print(s[::-1])
